name: Go

on:
  pull_request:
    paths: ["**.go", "go.mod", "go.sum"]

jobs:
  lint:
    name: Go lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5
      - uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # renovate: tag=v2.5.2
        with:
          version: latest

  build:
    name: Go build
    needs: [lint]
    strategy:
      matrix:
        platform: [aws_lambda]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5
      - uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57 # renovate: tag=v2.1.4
        with:
          go-version: 1.17.x
      - name: Build github-quick-actions for ${{ matrix.platform }}
        run: >-
          go build -tags ${{ matrix.platform }} -o github-quick-actions -ldflags "
          -X github.com/prometheus/common/version.Version=${GITHUB_REF##*/}
          -X github.com/prometheus/common/version.Revision=${{ github.sha }}
          -X github.com/prometheus/common/version.Branch=${{ github.head_ref }}
          -X github.com/prometheus/common/version.BuildUser=${{ github.actor }}@github.${{ github.run_id }}
          -X github.com/prometheus/common/version.BuildDate=$(date --iso-8601=seconds)
          "

  test:
    name: Go test & coverage
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5
      - uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57 # renovate: tag=v2.1.4
        with:
          go-version: 1.17.x
      - run: go test -cover -race -coverprofile cover.out -v ./...
      - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # renovate: tag=v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cover.out
          flags: unittests
          verbose: true
