name: Security hardening (Github Actions workflows)

on:
  pull_request:
    types: [opened, synchronize]
    paths: [".github/workflows/**"]
  push:
    branches: [master]
    paths: [".github/workflows/**"]

jobs:
  ci_harden_security:
    name: Security hardening (Github Actions workflows)
    uses: xunleii/github-actions-grimoire/.github/workflows/security.workflows.yaml@ef77ef160b177b1305af17a4e8ab9b560c2541da
