name: Security hardening (Github Actions workflows)

on:
  pull_request:
    types: [opened, synchronize]
    paths: [".github/workflows/**"]
  push:
    branches: [master]
    paths: [".github/workflows/**"]

jobs:
  ci_harden_security:
    name: Github Action security hardening
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@afe4af09a72596f47d806ee5f8b2674ec07fdc73
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43 #v1.0.4
