name: Terraform

on:
  pull_request:
    paths: ["deployments/**.tf"]

jobs:
  terraform:
    name: IaaS - Terraform CI (for pull requests)
    uses: xunleii/github-actions-grimoire/.github/workflows/terraform.pull_requests.yaml@0ab2cd93e86642397ecdfb2da1e5b97594ab9905
