name: Terraform

on:
  pull_request:
    paths: ["deployments/**.tf"]

jobs:
  terraform:
    name: IaaS - Terraform CI (for pull requests)
    uses: xunleii/github-actions-grimoire/.github/workflows/terraform.pull_requests.yaml@ef77ef160b177b1305af17a4e8ab9b560c2541da
