name: Terraform

on:
  pull_request:
    paths: ["deployments/**.tf"]

jobs:
  lint:
    name: Terraform lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@afe4af09a72596f47d806ee5f8b2674ec07fdc73
      - uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec #v1.3.2
      - run: terraform init -backend=false
      - run: terraform fmt -check -recursive -diff -no-color
