name: Terraform

on:
  pull_request:
    paths: ["deployments/**.tf"]

jobs:
  lint:
    name: Terraform lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5
      - uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec # renovate: tag=v1.3.2
      - run: terraform init -backend=false
      - run: terraform fmt -check -recursive -diff -no-color
