name: Terraform

on:
  pull_request:
    paths: ["deployments/**.tf"]

jobs:
  lint:
    name: Terraform lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2.3.4
      - uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec #v1.3.2
      - run: terraform init -backend=false
      - run: terraform fmt -check -recursive -diff -no-color
